#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
    CREATE USER ${SPRING_DATASOURCE_USERNAME} WITH PASSWORD '${SPRING_DATASOURCE_PASSWORD}' LOGIN;
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${SPRING_DATASOURCE_USERNAME};
    GRANT USAGE, CREATE ON SCHEMA public TO ${SPRING_DATASOURCE_USERNAME};
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${SPRING_DATASOURCE_USERNAME};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${SPRING_DATASOURCE_USERNAME};
EOSQL