syntax = "proto3";

option java_package = "ru.kirillvodu.grpc.user";
option java_outer_classname = "UserServiceProto";
option java_multiple_files = true;

service UserGrpcService {
  rpc GetUserById(GetUserByIdRequest) returns (GetUserByIdResponse);
  rpc GetUsersByIds(GetUsersByIdsRequest) returns (GetUsersByIdsResponse);
}

message UserProto {
  string id = 1;
  string name = 2;
}

message GetUserByIdRequest {
  string id = 1;
}

message GetUserByIdResponse {
  UserProto user = 1;
  bool found = 2;
}

message GetUsersByIdsRequest {
  repeated string ids = 1;
}

message GetUsersByIdsResponse {
  repeated UserProto users = 1;
}
