#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${SPRING_DATASOURCE_USERNAME} WITH PASSWORD '${SPRING_DATASOURCE_PASSWORD}' LOGIN CREATEROLE;
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${SPRING_DATASOURCE_USERNAME};
    GRANT USAGE, CREATE ON SCHEMA public TO ${SPRING_DATASOURCE_USERNAME} WITH GRANT OPTION;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${SPRING_DATASOURCE_USERNAME};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${SPRING_DATASOURCE_USERNAME};

    CREATE USER ${DEBEZIUM_USER} WITH PASSWORD '${DEBEZIUM_PASSWORD}' REPLICATION LOGIN;
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DEBEZIUM_USER};
    GRANT USAGE ON SCHEMA public TO ${DEBEZIUM_USER};
    GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${DEBEZIUM_USER};
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DEBEZIUM_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${SPRING_DATASOURCE_USERNAME} IN SCHEMA public
    GRANT SELECT ON TABLES TO ${DEBEZIUM_USER};
EOSQL