server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8085/realms/dorogame_realm}

grpc:
  server:
    port: 9090

keycloak:
  admin:
    server-url: ${KEYCLOAK_ADMIN_SERVER_URL:http://localhost:8085}
    realm: ${KEYCLOAK_ADMIN_REALM:dorogame_realm}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:dorogame_backend_api}
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
